site_name: 'ZenKit'
site_url: 'https://zk.gothickit.dev'
copyright: 'Copyright © 2022-2023 GothicKit Contributors.'
repo_url: 'https://github.com/GothicKit/ZenKit'
edit_uri: 'edit/main/docs/'
theme:
  name: 'material'
  language: 'en'
  logo: 'assets/logo-square.png'
  favicon: 'assets/logo-square.png'
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    scheme: 'slate'
    primary: 'red'
  features:
    - 'navigation.instant'
    - 'navigation.tabs'
    - 'navigation.sections'
    - 'navigation.expand'
    - 'search.suggest'
    - 'search.highlight'
    - 'content.tabs.link'
    - 'content.code.copy'
    - 'content.code.annotate'
extra_css:
  - 'assets/stylesheets/extra.css'
extra_javascript:
  - 'assets/javascript/mathjax.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
plugins:
  - 'search'
  - literate-nav:
      nav_file: 'SUMMARY.md'
  - 'section-index'
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - 'abbr'
  - 'admonition'
  - 'footnotes'
  - 'tables'
  - 'pymdownx.superfences'
  - 'pymdownx.inlinehilite'
  - 'md_in_html'
  - 'pymdownx.details'
  - 'def_list'
  - 'attr_list'
