site_name: 'ZenKit'
site_url: 'https://zk.gothickit.dev'
copyright: 'Copyright © 2022-2023 GothicKit Contributors.'
repo_url: 'https://github.com/GothicKit/phoenix'
edit_uri: 'edit/main/docs/'
nav:
  - 'Library Reference':
      - 'Overview': 'library/overview.md'
      - 'Getting Started': 'library/quickstart.md'
      - 'File Type Reference': 'library/reference.md'
      - 'Miscellaneous':
          - 'Migration Guide (v1.2 ➞ v1.3)': 'library/misc/v1.2-to-v1.3.md'
      - 'ZenKit Concepts':
          - 'Archive': 'library/api/archive.md'
          - 'Cutscene Library': 'library/api/cutscene-library.md'
          - 'Daedalus Script': 'library/api/daedalus-script.md'
          - 'Daedalus VM': 'library/api/daedalus-vm.md'
          - 'Font': 'library/api/font.md'
          - 'Mesh': 'library/api/mesh.md'
          - 'Model': 'library/api/model.md'
          - 'Model Animation': 'library/api/model-animation.md'
          - 'Model Hierarchy': 'library/api/model-hierarchy.md'
          - 'Model Mesh': 'library/api/model-mesh.md'
          - 'Model Script': 'library/api/model-script.md'
          - 'Morph Mesh': 'library/api/morph-mesh.md'
          - 'Multi-Resolution Mesh': 'library/api/multi-resolution-mesh.md'
          - 'Save Game': 'library/api/save-game.md'
          - 'Texture': 'library/api/texture.md'
          - 'Virtual File System': 'library/api/virtual-file-system.md'
          - 'World': 'library/api/world.md'
  - 'ZenGin Reference':
      - 'Overview': 'engine/overview.md'
      - 'Datatypes': 'engine/datatypes.md'
      - 'Formats':
          - 'ZenGin Animations': 'engine/formats/animation.md'
          - 'ZenGin Font': 'engine/formats/font.md'
          - 'ZenGin Texture': 'engine/formats/texture.md'
          - 'ZenGin Virtual File System': 'engine/formats/vdf.md'
          - 'ZenGin Archive': 'engine/formats/archive.md'
      - 'Objects':
          - 'zCVob': 'engine/objects/zCVob.md'
          - 'zCVobAnimate': 'engine/objects/zCVobAnimate.md'
          - 'zCVobLensFlare': 'engine/objects/zCVobLensFlare.md'
          - 'zCVobLevelCompo': 'engine/objects/zCVobLevelCompo.md'
          - 'zCVobLight': 'engine/objects/zCVobLight.md'
          - 'zCVobScreenFX': 'engine/objects/zCVobScreenFX.md'
          - 'zCVobSound': 'engine/objects/zCVobSound.md'
          - 'zCVobSpot': 'engine/objects/zCVobSpot.md'
          - 'zCVobStair': 'engine/objects/zCVobStair.md'
          - 'zCVobStartpoint': 'engine/objects/zCVobStartpoint.md'
          - 'oCMOB': 'engine/objects/oCMOB.md'
          - 'oCMobInter': 'engine/objects/oCMobInter.md'
          - 'oCMobBed': 'engine/objects/oCMobBed.md'
          - 'oCMobContainer': 'engine/objects/oCMobContainer.md'
          - 'oCMobDoor': 'engine/objects/oCMobDoor.md'
          - 'oCMobFire': 'engine/objects/oCMobFire.md'
          - 'oCMobLadder': 'engine/objects/oCMobLadder.md'
          - 'oCMobSwitch': 'engine/objects/oCMobSwitch.md'
          - 'oCMobWheel': 'engine/objects/oCMobWheel.md'
          - 'zCCodeMaster': 'engine/objects/zCCodeMaster.md'
          - 'zCEarthquake': 'engine/objects/zCEarthquake.md'
          - 'zCMessageFilter': 'engine/objects/zCMessageFilter.md'
          - 'zCMoverControler': 'engine/objects/zCMoverController.md'
          - 'zCPFXControler': 'engine/objects/zCPFXControler.md'
          - 'zCTouchDamage': 'engine/objects/zCTouchDamage.md'
          - 'oCItem': 'engine/objects/oCItem.md'
          - 'zCVisual': 'engine/objects/zCVisual.md'
          - 'zCDecal': 'engine/objects/zCDecal.md'
      - 'Encodings':
          - 'Binary': 'engine/encodings/binary.md'
          - 'Binary, Chunked': 'engine/encodings/binary-chunked.md'
theme:
  name: 'material'
  language: 'en'
  logo: 'assets/logo-square.png'
  favicon: 'assets/logo-square.png'
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    scheme: 'slate'
    primary: 'red'
  features:
    - 'navigation.instant'
    - 'navigation.tabs'
    - 'navigation.sections'
    - 'navigation.expand'
    - 'search.suggest'
    - 'search.highlight'
    - 'content.tabs.link'
    - 'content.code.copy'
    - 'content.code.annotate'
extra_css:
  - 'assets/stylesheets/extra.css'
extra_javascript:
  - 'assets/javascript/mathjax.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
plugins:
  - 'search'
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - 'abbr'
  - 'admonition'
  - 'footnotes'
  - 'tables'
  - 'pymdownx.superfences'
  - 'pymdownx.inlinehilite'
  - 'md_in_html'
  - 'pymdownx.details'
  - 'def_list'
